"""
PR Creator: Creates pull requests with refactoring changes.
"""

import subprocess
from typing import List, Dict, Any, Optional
from dataclasses import dataclass, field
from pathlib import Path
from datetime import datetime
import json

from .refactorer import Refactoring, RefactoringHistory


@dataclass
class PRMetadata:
    """Metadata for a pull request."""
    title: str
    description: str
    branch_name: str
    files_changed: List[str]
    refactorings: List[Refactoring]
    breaking_changes: bool = False
    test_updates_needed: bool = False
    estimated_review_time: str = "15 min"
    labels: List[str] = field(default_factory=list)


class PRCreator:
    """
    Creates pull requests for refactoring changes.
    """
    
    def __init__(self, repo_path: Optional[Path] = None):
        self.repo_path = repo_path or Path.cwd()
        self.refactoring_history: Dict[str, RefactoringHistory] = {}
    
    def create_refactoring_pr(
        self,
        refactorings: List[Refactoring],
        base_branch: str = "main",
        auto_create: bool = False
    ) -> PRMetadata:
        """
        Create a pull request for refactoring changes.
        
        Args:
            refactorings: List of refactorings to include
            base_branch: Base branch for the PR
            auto_create: Whether to actually create the branch and PR
            
        Returns:
            PRMetadata
        """
        # Generate branch name
        branch_name = self._generate_branch_name(refactorings)
        
        # Generate PR title and description
        title = self._generate_pr_title(refactorings)
        description = self._generate_pr_description(refactorings)
        
        # Collect files changed
        files_changed = list(set(r.filename for r in refactorings))
        
        # Check for breaking changes
        breaking_changes = any(r.breaking_change for r in refactorings)
        
        # Check if test updates needed
        test_updates_needed = any(r.tests_needed for r in refactorings)
        
        # Generate labels
        labels = self._generate_labels(refactorings, breaking_changes)
        
        metadata = PRMetadata(
            title=title,
            description=description,
            branch_name=branch_name,
            files_changed=files_changed,
            refactorings=refactorings,
            breaking_changes=breaking_changes,
            test_updates_needed=test_updates_needed,
            labels=labels,
        )
        
        if auto_create:
            self._create_branch(metadata, base_branch)
            self._commit_changes(metadata)
            self._push_branch(metadata)
            pr_url = self._create_pr(metadata, base_branch)
            metadata.description += f"\n\nPR URL: {pr_url}"
        
        return metadata
    
    def _generate_branch_name(self, refactorings: List[Refactoring]) -> str:
        """Generate a branch name for the refactoring."""
        timestamp = datetime.now().strftime("%Y%m%d-%H%M%S")
        
        # Get primary refactoring type
        type_counts = {}
        for r in refactorings:
            type_counts[r.refactoring_type.name] = type_counts.get(r.refactoring_type.name, 0) + 1
        
        primary_type = max(type_counts, key=type_counts.get) if type_counts else "refactor"
        
        return f"refactor/{primary_type.lower()}-{timestamp}"
    
    def _generate_pr_title(self, refactorings: List[Refactoring]) -> str:
        """Generate PR title."""
        type_counts = {}
        for r in refactorings:
            type_counts[r.refactoring_type.name] = type_counts.get(r.refactoring_type.name, 0) + 1
        
        if len(type_counts) == 1:
            refactoring_type = list(type_counts.keys())[0].replace('_', ' ').title()
            return f"Refactor: {refactoring_type} improvements"
        else:
            total = len(refactorings)
            return f"Refactor: Multiple improvements ({total} changes)"
    
    def _generate_pr_description(self, refactorings: List[Refactoring]) -> str:
        """Generate detailed PR description."""
        lines = [
            "## 🤖 Automated Refactoring",
            "",
            "This PR contains automated code improvements generated by the refactoring agent.",
            "",
            "### Summary",
            f"- **Total refactorings:** {len(refactorings)}",
            f"- **Files modified:** {len(set(r.filename for r in refactorings))}",
            "",
            "### Changes",
            "",
        ]
        
        # Group by refactoring type
        by_type: Dict[str, List[Refactoring]] = {}
        for r in refactorings:
            type_name = r.refactoring_type.name
            if type_name not in by_type:
                by_type[type_name] = []
            by_type[type_name].append(r)
        
        for type_name, type_refactorings in by_type.items():
            lines.extend([
                f"#### {type_name.replace('_', ' ').title()}",
                "",
            ])
            for r in type_refactorings:
                lines.append(f"- **{r.filename}** (lines {r.line_start}-{r.line_end})")
                lines.append(f"  - {r.description}")
                lines.append(f"  - Confidence: {r.confidence:.0%}")
                if r.breaking_change:
                    lines.append("  - ⚠️ **Breaking Change**")
                lines.append("")
        
        # Add verification checklist
        lines.extend([
            "### Verification Checklist",
            "",
            "- [ ] Code review completed",
            "- [ ] Tests pass",
            "- [ ] No behavioral changes",
            "- [ ] Documentation updated (if needed)",
            "",
        ])
        
        # Add detailed changes section
        lines.extend([
            "### Detailed Changes",
            "",
            "<details>",
            "<summary>Click to expand</summary>",
            "",
        ])
        
        for r in refactorings:
            lines.extend([
                f"**{r.filename}:{r.line_start}-{r.line_end}**",
                "",
                "Description:",
                f"```\n{r.description}\n```",
                "",
                "Verification Steps:",
            ])
            for step in r.verification_steps:
                lines.append(f"- {step}")
            lines.append("")
        
        lines.extend([
            "</details>",
            "",
            "---",
            "*Generated by RobeetsDay Autonomous Refactoring Agent*",
        ])
        
        return '\n'.join(lines)
    
    def _generate_labels(
        self, 
        refactorings: List[Refactoring],
        breaking_changes: bool
    ) -> List[str]:
        """Generate PR labels."""
        labels = ["refactoring", "automated"]
        
        if breaking_changes:
            labels.append("breaking-change")
        
        # Add labels based on refactoring types
        for r in refactorings:
            label = r.refactoring_type.name.lower().replace('_', '-')
            if label not in labels:
                labels.append(label)
        
        return labels
    
    def _create_branch(self, metadata: PRMetadata, base_branch: str):
        """Create a git branch."""
        try:
            # Checkout base branch
            subprocess.run(
                ['git', 'checkout', base_branch],
                cwd=self.repo_path,
                check=True,
                capture_output=True
            )
            
            # Pull latest changes
            subprocess.run(
                ['git', 'pull', 'origin', base_branch],
                cwd=self.repo_path,
                check=True,
                capture_output=True
            )
            
            # Create new branch
            subprocess.run(
                ['git', 'checkout', '-b', metadata.branch_name],
                cwd=self.repo_path,
                check=True,
                capture_output=True
            )
        except subprocess.CalledProcessError as e:
            raise RuntimeError(f"Failed to create branch: {e}")
    
    def _commit_changes(self, metadata: PRMetadata):
        """Commit refactoring changes."""
        try:
            # Stage changes
            subprocess.run(
                ['git', 'add', '.'],
                cwd=self.repo_path,
                check=True,
                capture_output=True
            )
            
            # Create commit
            commit_message = self._generate_commit_message(metadata)
            subprocess.run(
                ['git', 'commit', '-m', commit_message],
                cwd=self.repo_path,
                check=True,
                capture_output=True
            )
        except subprocess.CalledProcessError as e:
            raise RuntimeError(f"Failed to commit changes: {e}")
    
    def _generate_commit_message(self, metadata: PRMetadata) -> str:
        """Generate commit message."""
        lines = [
            f"refactor: {metadata.title}",
            "",
            "Changes:",
        ]
        
        for r in metadata.refactorings:
            lines.append(f"- {r.description}")
        
        return '\n'.join(lines)
    
    def _push_branch(self, metadata: PRMetadata):
        """Push branch to remote."""
        try:
            subprocess.run(
                ['git', 'push', '-u', 'origin', metadata.branch_name],
                cwd=self.repo_path,
                check=True,
                capture_output=True
            )
        except subprocess.CalledProcessError as e:
            raise RuntimeError(f"Failed to push branch: {e}")
    
    def _create_pr(self, metadata: PRMetadata, base_branch: str) -> str:
        """Create PR using GitHub CLI."""
        try:
            result = subprocess.run(
                [
                    'gh', 'pr', 'create',
                    '--title', metadata.title,
                    '--body', metadata.description,
                    '--base', base_branch,
                    '--head', metadata.branch_name,
                    '--label', ','.join(metadata.labels),
                ],
                cwd=self.repo_path,
                capture_output=True,
                text=True
            )
            
            if result.returncode == 0:
                return result.stdout.strip()
            else:
                raise RuntimeError(f"Failed to create PR: {result.stderr}")
        except FileNotFoundError:
            return "GitHub CLI not available - create PR manually"
        except subprocess.CalledProcessError as e:
            raise RuntimeError(f"Failed to create PR: {e}")
    
    def save_refactoring_history(self, output_path: Path):
        """Save refactoring history to a file."""
        history_data = {
            "saved_at": datetime.now().isoformat(),
            "files": {}
        }
        
        for filename, history in self.refactoring_history.items():
            history_data["files"][filename] = {
                "refactorings": [
                    {
                        "type": r.refactoring_type.name,
                        "description": r.description,
                        "line_start": r.line_start,
                        "line_end": r.line_end,
                        "confidence": r.confidence,
                    }
                    for r in history.refactorings
                ],
                "rejected": [
                    {
                        "refactoring": {
                            "type": r.refactoring_type.name,
                            "description": r.description,
                        },
                        "reason": reason
                    }
                    for r, reason in history.rejected
                ],
                "success_rate": history.get_success_rate()
            }
        
        output_path.write_text(json.dumps(history_data, indent=2))
    
    def load_refactoring_history(self, input_path: Path):
        """Load refactoring history from a file."""
        if not input_path.exists():
            return
        
        data = json.loads(input_path.read_text())
        
        for filename, file_data in data.get("files", {}).items():
            history = RefactoringHistory()
            # Note: This is a simplified restore - full implementation would
            # need to reconstruct Refactoring objects
            self.refactoring_history[filename] = history
    
    def generate_refactoring_report(
        self, 
        project_path: Path,
        output_path: Optional[Path] = None
    ) -> str:
        """Generate a comprehensive refactoring report for the project."""
        lines = [
            "# Refactoring Report",
            "",
            f"Generated: {datetime.now().isoformat()}",
            f"Project: {project_path}",
            "",
            "## Summary",
            "",
        ]
        
        total_refactorings = sum(
            len(h.refactorings) for h in self.refactoring_history.values()
        )
        total_rejected = sum(
            len(h.rejected) for h in self.refactoring_history.values()
        )
        
        lines.extend([
            f"- Total refactorings applied: {total_refactorings}",
            f"- Total refactorings rejected: {total_rejected}",
            f"- Success rate: {total_refactorings / (total_refactorings + total_rejected):.1%}",
            "",
            "## By File",
            "",
        ])
        
        for filename, history in sorted(self.refactoring_history.items()):
            lines.extend([
                f"### {filename}",
                "",
                f"- Applied: {len(history.refactorings)}",
                f"- Rejected: {len(history.rejected)}",
                f"- Success rate: {history.get_success_rate():.1%}",
                "",
            ])
            
            if history.refactorings:
                lines.append("**Applied refactorings:**")
                for r in history.refactorings:
                    lines.append(f"- {r.refactoring_type.name}: {r.description}")
                lines.append("")
        
        report = '\n'.join(lines)
        
        if output_path:
            output_path.write_text(report)
        
        return report
