"""
Generator module for auto-documentation.
Generates and updates AGENTS.md and other documentation files.
"""

import re
from typing import List, Dict, Any, Optional
from pathlib import Path
from datetime import datetime
from dataclasses import dataclass
from jinja2 import Template
from loguru import logger

from .diff import CodeChange, ChangeType, DiffAnalyzer


@dataclass
class DocumentationSection:
    """Represents a section in the documentation."""
    title: str
    content: str
    level: int  # Header level (1-6)
    order: int
    tags: List[str]
    last_updated: datetime


class AGENTSMDGenerator:
    """Generator for AGENTS.md files."""
    
    # Default template for AGENTS.md
    DEFAULT_TEMPLATE = """# {{ project_name }} - Agent Knowledge Base

> **Last Updated:** {{ last_updated }}
> **Version:** {{ version }}

## Project Overview

{{ overview }}

## Architecture

{{ architecture }}

## Key Components

{% for component in components %}
### {{ component.name }}

{{ component.description }}

**Location:** `{{ component.location }}`

{% endfor %}

## API Endpoints

{% for route in routes %}
### {{ route.method }} {{ route.path }}

{{ route.description }}

{% endfor %}

## Database Models

{% for model in models %}
### {{ model.name }}

{{ model.description }}

**Fields:**
{% for field in model.fields %}
- `{{ field.name }}` ({{ field.type }})
{% endfor %}

{% endfor %}

## Recent Changes

{% if changes %}
{% for change in changes %}
- **{{ change.change_type.value }}**: {{ change.description }} (`{{ change.file_path }}`)
{% endfor %}
{% else %}
No recent changes recorded.
{% endif %}

## Development Guidelines

{{ guidelines }}

---
*This file is auto-generated by the Auto-Documentation skill.*
"""
    
    def __init__(self, project_root: Path, template: Optional[str] = None):
        self.project_root = Path(project_root)
        self.template = Template(template or self.DEFAULT_TEMPLATE)
        self.analyzer = DiffAnalyzer()
        self.agents_md_path = self.project_root / "AGENTS.md"
    
    def generate(
        self,
        changes: List[CodeChange],
        project_info: Optional[Dict[str, Any]] = None
    ) -> str:
        """
        Generate AGENTS.md content.
        
        Args:
            changes: List of code changes to document
            project_info: Optional project metadata
            
        Returns:
            Generated markdown content
        """
        project_info = project_info or self._detect_project_info()
        
        # Extract components from changes
        components = self._extract_components(changes)
        routes = self._extract_routes(changes)
        models = self._extract_models(changes)
        
        # Prepare template data
        data = {
            'project_name': project_info.get('name', 'Project'),
            'version': project_info.get('version', '1.0.0'),
            'last_updated': datetime.now().strftime('%Y-%m-%d %H:%M:%S'),
            'overview': project_info.get('overview', self._generate_overview(changes)),
            'architecture': project_info.get('architecture', self._generate_architecture(changes)),
            'components': components,
            'routes': routes,
            'models': models,
            'changes': changes[:20],  # Last 20 changes
            'guidelines': project_info.get('guidelines', self._generate_guidelines()),
        }
        
        return self.template.render(**data)
    
    def update(
        self,
        changes: List[CodeChange],
        preserve_existing: bool = True
    ) -> str:
        """
        Update existing AGENTS.md with new changes.
        
        Args:
            changes: New code changes
            preserve_existing: Whether to preserve existing sections
            
        Returns:
            Updated markdown content
        """
        if not self.agents_md_path.exists() or not preserve_existing:
            return self.generate(changes)
        
        existing_content = self.agents_md_path.read_text(encoding='utf-8')
        
        # Update version history
        updated_content = self._update_version_history(existing_content, changes)
        
        # Update API section if routes changed
        updated_content = self._update_api_section(updated_content, changes)
        
        # Update models section if models changed
        updated_content = self._update_models_section(updated_content, changes)
        
        # Update last updated timestamp
        updated_content = self._update_timestamp(updated_content)
        
        # Add "What's New" section
        updated_content = self._add_whats_new(updated_content, changes)
        
        return updated_content
    
    def save(self, content: str, output_path: Optional[Path] = None):
        """Save generated content to file."""
        output_path = output_path or self.agents_md_path
        output_path.write_text(content, encoding='utf-8')
        logger.info(f"Saved documentation to {output_path}")
    
    def _detect_project_info(self) -> Dict[str, Any]:
        """Detect project information from files."""
        info = {
            'name': self.project_root.name,
            'version': '1.0.0',
            'overview': '',
            'architecture': '',
            'guidelines': '',
        }
        
        # Try to read from package.json, pyproject.toml, etc.
        package_json = self.project_root / "package.json"
        if package_json.exists():
            import json
            data = json.loads(package_json.read_text())
            info['name'] = data.get('name', info['name'])
            info['version'] = data.get('version', info['version'])
            info['overview'] = data.get('description', '')
        
        pyproject_toml = self.project_root / "pyproject.toml"
        if pyproject_toml.exists():
            try:
                import tomllib
                data = tomllib.loads(pyproject_toml.read_text())
                if 'project' in data:
                    info['name'] = data['project'].get('name', info['name'])
                    info['version'] = data['project'].get('version', info['version'])
                    info['overview'] = data['project'].get('description', '')
            except:
                pass
        
        return info
    
    def _extract_components(self, changes: List[CodeChange]) -> List[Dict[str, str]]:
        """Extract components from changes."""
        components = []
        
        # Group by directory
        dir_components = {}
        for change in changes:
            dir_path = Path(change.file_path).parent
            if str(dir_path) not in dir_components:
                dir_components[str(dir_path)] = []
            dir_components[str(dir_path)].append(change)
        
        for dir_path, dir_changes in dir_components.items():
            if len(dir_changes) > 0:
                components.append({
                    'name': dir_path.replace('/', ' ').title(),
                    'description': f"Contains {len(dir_changes)} recent changes",
                    'location': dir_path,
                })
        
        return components[:10]  # Limit to 10 components
    
    def _extract_routes(self, changes: List[CodeChange]) -> List[Dict[str, str]]:
        """Extract API routes from changes."""
        routes = []
        
        for change in changes:
            if change.element_type == 'route':
                parts = change.name.split(' ', 1)
                method = parts[0] if len(parts) > 0 else 'GET'
                path = parts[1] if len(parts) > 1 else '/'
                
                routes.append({
                    'method': method,
                    'path': path,
                    'description': change.description,
                })
        
        return routes
    
    def _extract_models(self, changes: List[CodeChange]) -> List[Dict[str, Any]]:
        """Extract database models from changes."""
        models = []
        
        for change in changes:
            if change.element_type == 'model':
                models.append({
                    'name': change.name,
                    'description': change.description,
                    'fields': [],  # Would need deeper parsing
                })
        
        return models
    
    def _generate_overview(self, changes: List[CodeChange]) -> str:
        """Generate project overview from changes."""
        categorized = self.analyzer.categorize_changes(changes)
        
        parts = ["This project is a software application with the following characteristics:"]
        
        if categorized['new_features']:
            parts.append(f"\n- Contains {len(categorized['new_features'])} recently added features")
        
        if categorized['routes']:
            routes = [c for c in changes if c.element_type == 'route']
            parts.append(f"\n- Has {len(routes)} API endpoints")
        
        if categorized.get('models', []):
            models = [c for c in changes if c.element_type == 'model']
            parts.append(f"\n- Uses {len(models)} database models")
        
        return '\n'.join(parts)
    
    def _generate_architecture(self, changes: List[CodeChange]) -> str:
        """Generate architecture description."""
        # Detect tech stack from file types
        has_python = any('python' in c.file_path or c.file_path.endswith('.py') for c in changes)
        has_js = any(c.file_path.endswith(('.js', '.ts')) for c in changes)
        
        parts = []
        
        if has_python:
            parts.append("- **Backend:** Python (likely FastAPI/Flask/Django)")
        
        if has_js:
            parts.append("- **Frontend:** JavaScript/TypeScript")
        
        parts.append("- **Documentation:** Auto-generated AGENTS.md")
        
        return '\n'.join(parts)
    
    def _generate_guidelines(self) -> str:
        """Generate development guidelines."""
        return """1. Follow existing code patterns
2. Add docstrings to new functions and classes
3. Update AGENTS.md when making significant changes
4. Run tests before committing
5. Use type hints where appropriate
"""
    
    def _update_version_history(self, content: str, changes: List[CodeChange]) -> str:
        """Update version history section."""
        # Find or create version history section
        if '## Version History' not in content:
            content += "\n\n## Version History\n\n"
        
        # Add new entries
        new_entries = []
        for change in changes[:10]:  # Last 10 changes
            timestamp = datetime.now().strftime('%Y-%m-%d')
            new_entries.append(f"- [{timestamp}] {change.change_type.value}: {change.description}")
        
        # Insert after section header
        section_pattern = r'(## Version History\n+)'
        if new_entries:
            new_section = f"## Version History\n\n" + '\n'.join(new_entries) + '\n\n'
            content = re.sub(section_pattern, new_section, content)
        
        return content
    
    def _update_api_section(self, content: str, changes: List[CodeChange]) -> str:
        """Update API documentation section."""
        route_changes = [c for c in changes if c.element_type == 'route']
        
        if not route_changes:
            return content
        
        # Find API section or add it
        if '## API Endpoints' not in content:
            content += "\n\n## API Endpoints\n\n"
        
        # Add new routes
        new_routes = []
        for change in route_changes[:5]:
            parts = change.name.split(' ', 1)
            method = parts[0] if len(parts) > 0 else 'GET'
            path = parts[1] if len(parts) > 1 else '/'
            new_routes.append(f"### {method} {path}\n\n{change.description}\n")
        
        # Insert after API section header
        if new_routes:
            section_end = content.find('## API Endpoints') + len('## API Endpoints')
            content = content[:section_end] + '\n\n' + '\n'.join(new_routes) + content[section_end:]
        
        return content
    
    def _update_models_section(self, content: str, changes: List[CodeChange]) -> str:
        """Update models documentation section."""
        model_changes = [c for c in changes if c.element_type == 'model']
        
        if not model_changes:
            return content
        
        if '## Database Models' not in content:
            content += "\n\n## Database Models\n\n"
        
        # Add new models
        new_models = []
        for change in model_changes[:5]:
            new_models.append(f"### {change.name}\n\n{change.description}\n")
        
        if new_models:
            section_end = content.find('## Database Models') + len('## Database Models')
            content = content[:section_end] + '\n\n' + '\n'.join(new_models) + content[section_end:]
        
        return content
    
    def _update_timestamp(self, content: str) -> str:
        """Update last updated timestamp."""
        timestamp = datetime.now().strftime('%Y-%m-%d %H:%M:%S')
        
        # Update or add timestamp
        if '**Last Updated:**' in content:
            content = re.sub(
                r'\*\*Last Updated:\*\* [^\n]+',
                f'**Last Updated:** {timestamp}',
                content
            )
        else:
            # Add near the top
            content = f"> **Last Updated:** {timestamp}\n\n{content}"
        
        return content
    
    def _add_whats_new(self, content: str, changes: List[CodeChange]) -> str:
        """Add or update "What's New" section."""
        if not changes:
            return content
        
        whats_new = ["## What's New\n"]
        
        categorized = self.analyzer.categorize_changes(changes)
        
        if categorized['new_features']:
            whats_new.append("\n### ✨ New Features")
            for change in categorized['new_features'][:5]:
                whats_new.append(f"- {change.description}")
        
        if categorized['bugfixes']:
            whats_new.append("\n### 🐛 Bug Fixes")
            for change in categorized['bugfixes'][:3]:
                whats_new.append(f"- {change.description}")
        
        # Remove old What's New section if exists
        content = re.sub(r'## What\'s New.*?(?=##|$)', '', content, flags=re.DOTALL)
        
        # Add new section after first header
        first_header_end = content.find('\n## ')
        if first_header_end > 0:
            content = content[:first_header_end] + '\n' + '\n'.join(whats_new) + '\n' + content[first_header_end:]
        else:
            content += '\n\n' + '\n'.join(whats_new)
        
        return content


class WhatsNewGenerator:
    """Generator for "What's New" summaries."""
    
    def generate(
        self,
        changes: List[CodeChange],
        since: Optional[datetime] = None
    ) -> str:
        """
        Generate a "What's New" summary.
        
        Args:
            changes: List of code changes
            since: Only include changes since this date
            
        Returns:
            Markdown formatted summary
        """
        if since:
            changes = [c for c in changes if True]  # Would filter by timestamp
        
        analyzer = DiffAnalyzer()
        categorized = analyzer.categorize_changes(changes)
        summary = analyzer.get_summary(changes)
        
        lines = ["# What's New\n"]
        
        # Summary stats
        lines.append(f"**{summary['total_changes']} changes** detected.\n")
        
        # New features
        if categorized['new_features']:
            lines.append("## ✨ New Features\n")
            for change in categorized['new_features'][:10]:
                lines.append(f"- **{change.name}** ({change.element_type})")
                lines.append(f"  - {change.description}")
                lines.append(f"  - Location: `{change.file_path}:{change.line_numbers[0] if change.line_numbers else '?'}`")
                lines.append("")
        
        # Bug fixes
        if categorized['bugfixes']:
            lines.append("## 🐛 Bug Fixes\n")
            for change in categorized['bugfixes'][:5]:
                lines.append(f"- {change.description}")
            lines.append("")
        
        # API changes
        routes = [c for c in changes if c.element_type == 'route']
        if routes:
            lines.append("## 🔌 API Changes\n")
            for change in routes[:5]:
                lines.append(f"- `{change.name}` - {change.description}")
            lines.append("")
        
        # Model changes
        models = [c for c in changes if c.element_type == 'model']
        if models:
            lines.append("## 🗄️ Database Changes\n")
            for change in models[:5]:
                lines.append(f"- **{change.name}** - {change.description}")
            lines.append("")
        
        # High impact changes
        if summary['high_impact_changes']:
            lines.append("## ⚠️ High Impact Changes\n")
            for change in summary['high_impact_changes'][:5]:
                lines.append(f"- **{change['name']}** - {change['description']}")
            lines.append("")
        
        return '\n'.join(lines)
