apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: mb7-staging

resources:
- ../../

namePrefix: staging-

commonLabels:
  environment: staging

patchesStrategicMerge:
- replica-patch.yml

configMapGenerator:
- name: mb7-config
  behavior: merge
  literals:
  - LOG_LEVEL=DEBUG
  - YOLO_SAFETY_THRESHOLD=0.5
  - FEATURE_AUTO_ROLLBACK=false
